name: build

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 0 * * WED'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASS }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build 18
        shell: bash
        run: |
          docker build --build-arg IMAGE_VERSION=18 -t aasaam/node-lts-plus:18 .
          docker push aasaam/node-lts-plus:18
          docker tag aasaam/node-lts-plus:18 ghcr.io/aasaam/node-lts-plus:18
          docker push ghcr.io/aasaam/node-lts-plus:18

      - name: Build latest
        shell: bash
        run: |
          docker build --build-arg IMAGE_VERSION=20 -t aasaam/node-lts-plus:latest .
          docker push aasaam/node-lts-plus:latest
          docker tag aasaam/node-lts-plus:latest ghcr.io/aasaam/node-lts-plus:latest
          docker push ghcr.io/aasaam/node-lts-plus:latest

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASS }}
          repository: aasaam/node-lts-plus
